In [1]:
import pandas as pd
import numpy as np
from flaml import AutoML

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-07-15 10:21:59,204	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2025-07-15 10:21:59,347	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

In [2]:
DATA_FOLDER = "./"
df = pd.read_pickle(DATA_FOLDER + "df_fe_epic_big_best_customers_2c.pickle")
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
product_ids = pd.read_csv(DATA_FOLDER + "product_id_apredecir201912.txt", sep="\t")[
    "product_id"
].tolist()
df = df[df["product_id"].isin(product_ids)]
df = df.sort_values(by=["date_id", "product_id"])
df["target"] = df.groupby(["product_id", "customer_id"])["tn"].shift(-2)

/tmp/ipykernel_59591/2984009778.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["target"] = df.groupby(["product_id", "customer_id"])["tn"].shift(-2)

In [3]:
df = df.drop(columns=["fecha", "periodo_min_producto", "periodo_max_producto", "periodo_min_customer", "periodo_max_customer"], errors="ignore")
# transformo todas las columnas object en categoricas
for col in df.select_dtypes(include=["object"]).columns:
    df[col] = df[col].astype("category")
df.describe()

,product_id,customer_id,plan_precios_cuidados,cust_request_qty,cust_request_tn,tn,stock_final,sku_size,year,mes,...,prod_tn_rolling_mean_24_x_tn_rolling_mean_12_lag_2,prod_tn_rolling_mean_24_x_tn_rolling_mean_24_lag_1,prod_tn_rolling_mean_24_x_tn_rolling_mean_12_lag_3,prod_tn_wavelet_0_mean_lag_6_x_tn_rolling_mean_12_lag_2,prod_tn_wavelet_0_mean_lag_6_x_tn_rolling_mean_24_lag_1,prod_tn_wavelet_0_mean_lag_6_x_tn_rolling_mean_12_lag_3,prod_tn_rolling_mean_12_lag_2_x_tn_rolling_mean_24_lag_1,prod_tn_rolling_mean_12_lag_2_x_tn_rolling_mean_12_lag_3,prod_tn_rolling_mean_24_lag_1_x_tn_rolling_mean_12_lag_3,target
count,67125.000000,67125.000000,44750.000000,67125.000000,67125.000000,67125.000000,32181.000000,67125.000000,67125.000000,67125.000000,...,2.056500e+04,1.886100e+04,2.056500e+04,3.877200e+04,1.886100e+04,3.680400e+04,1.886100e+04,3.680400e+04,1.886100e+04,62445.000000
mean,20479.289698,6667.666667,0.008894,74.170294,17.101440,16.724100,21.202147,447.860565,2018.112089,6.681475,...,4.618019e+03,4.851869e+03,4.665210e+03,4.519523e+03,4.800815e+03,4.571645e+03,4.638457e+03,4.733664e+03,4.682647e+03,16.957232
std,334.547874,4714.787452,0.093888,115.286339,67.551514,65.345131,60.536484,831.341003,0.813328,3.445673,...,4.854685e+04,4.798484e+04,4.859605e+04,4.565110e+04,4.699408e+04,4.585604e+04,4.862984e+04,4.778962e+04,4.876376e+04,66.435036
min,20001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-13.666560,1.000000,2017.000000,1.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,20200.000000,0.000000,0.000000,3.000000,0.110910,0.110790,1.422400,89.000000,2017.000000,4.000000,...,9.533407e-02,1.082089e-01,9.697029e-02,9.019850e-02,1.106257e-01,9.226073e-02,9.754751e-02,8.907180e-02,9.801301e-02,0.115910
50%,20411.000000,10001.000000,0.000000,11.000000,1.143290,1.139340,6.120440,220.000000,2018.000000,7.000000,...,2.828777e+00,2.942908e+00,2.846635e+00,2.616434e+00,2.973132e+00,2.672556e+00,2.854394e+00,2.579931e+00,2.883994e+00,1.161910
75%,20730.000000,10002.000000,0.000000,118.000000,8.066350,7.969530,19.142031,475.000000,2019.000000,10.000000,...,9.340449e+01,1.055332e+02,9.443301e+01,9.727163e+01,1.085154e+02,9.885401e+01,9.475851e+01,9.604533e+01,9.485516e+01,8.063050
max,21276.000000,10002.000000,1.000000,705.000000,2153.267822,2030.201416,1562.024536,10000.000000,2019.000000,12.000000,...,1.562886e+06,1.518555e+06,1.576501e+06,1.515214e+06,1.461905e+06,1.515214e+06,1.574931e+06,1.618976e+06,1.562886e+06,2030.201416

In [4]:
from sklearn.model_selection import BaseCrossValidator
import numpy as np

class CustomTimeSeriesSplit(BaseCrossValidator):
    def __init__(self, n_splits=3, gap=1):
        self.n_splits = n_splits
        self.gap = gap

    def get_n_splits(self, X=None, y=None, groups=None):
        return self.n_splits

    def split(self, X, y=None, groups=None):
        # Asegurar que X es DataFrame
        
        unique_dates = sorted(X["date_id"].unique(), reverse=True)
        
        for i in range(self.n_splits):
                
            test_date_id = unique_dates[i]
            train_date_id = test_date_id - self.gap - 1
            
            # Usar np.where para obtener posiciones enteras
            train_mask = X["date_id"] <= train_date_id
            test_mask = X["date_id"] == test_date_id
            
            train_idx = np.where(train_mask)[0]
            test_idx = np.where(test_mask)[0]
            
            yield train_idx, test_idx

In [5]:
def custom_metric(X_val, y_val, estimator, labels, X_train, y_train, *args, **kwargs):
    y_pred = estimator.predict(X_val)
    
    temp_df = pd.DataFrame({
        "product_id": X_val["product_id"].values,
        "y_true": y_val,
        "y_pred": y_pred
    })
    
    grouped = temp_df.groupby("product_id")[["y_true", "y_pred"]].sum()
    total_true = grouped["y_true"].sum()
    
    if total_true == 0:
        return 0.0, {"total_error": 0.0}
    
    total_error = np.abs(grouped["y_pred"] - grouped["y_true"]).sum() / total_true
    return total_error, {"total_error": total_error}

In [6]:
test_date = 33
train_date = 33
train_df = df[df["date_id"] <= train_date]
test_df = df[df["date_id"] == test_date]
X_train = train_df.drop("target", axis=1)
y_train = train_df["target"]
X_test = test_df.drop("target", axis=1)
y_test = test_df["target"]
tscv = CustomTimeSeriesSplit(n_splits=4, gap=1)
#time_budget = 1*60*60
time_budget = 3600
automl_settings = {
    "time_budget": time_budget,
    "task": "regression",
    "metric": custom_metric,
    "n_jobs": -1,
    "eval_method": "cv",
    "split_type": tscv,
    "verbose": 3,
    "retrain_full": True,
    "estimator_list": ['lgbm', 'xgboost', 'extra_tree', 'xgb_limitdepth', 'catboost']
}
automl = AutoML()

In [7]:
automl.fit(X_train=X_train, y_train=y_train, **automl_settings)

[flaml.automl.logger: 07-15 10:22:09] {1728} INFO - task = regression
[flaml.automl.logger: 07-15 10:22:09] {1739} INFO - Evaluation method: cv
[flaml.automl.logger: 07-15 10:22:09] {1838} INFO - Minimizing error metric: customized metric
[flaml.automl.logger: 07-15 10:22:09] {1955} INFO - List of ML learners in AutoML Run: ['lgbm', 'xgboost', 'extra_tree', 'xgb_limitdepth', 'catboost']
[flaml.automl.logger: 07-15 10:22:09] {2258} INFO - iteration 0, current learner lgbm
[flaml.automl.logger: 07-15 10:22:16] {2393} INFO - Estimated sufficient time budget=73744s. Estimated necessary time budget=616s.
[flaml.automl.logger: 07-15 10:22:16] {2442} INFO -  at 11.5s,	estimator lgbm's best error=1.0539,	best estimator lgbm's best error=1.0539
[flaml.automl.logger: 07-15 10:22:16] {2258} INFO - iteration 1, current learner lgbm
[flaml.automl.logger: 07-15 10:22:24] {2442} INFO -  at 19.1s,	estimator lgbm's best error=1.0539,	best estimator lgbm's best error=1.0539
[flaml.automl.logger: 07-15 10:22:24] {2258} INFO - iteration 2, current learner lgbm
[flaml.automl.logger: 07-15 10:22:31] {2442} INFO -  at 26.2s,	estimator lgbm's best error=0.6443,	best estimator lgbm's best error=0.6443
[flaml.automl.logger: 07-15 10:22:31] {2258} INFO - iteration 3, current learner xgboost
[flaml.automl.logger: 07-15 10:22:36] {2442} INFO -  at 31.3s,	estimator xgboost's best error=1.0515,	best estimator lgbm's best error=0.6443
[flaml.automl.logger: 07-15 10:22:36] {2258} INFO - iteration 4, current learner lgbm
[flaml.automl.logger: 07-15 10:22:44] {2442} INFO -  at 39.1s,	estimator lgbm's best error=0.3119,	best estimator lgbm's best error=0.3119
[flaml.automl.logger: 07-15 10:22:44] {2258} INFO - iteration 5, current learner lgbm
[flaml.automl.logger: 07-15 10:22:51] {2442} INFO -  at 46.0s,	estimator lgbm's best error=0.3119,	best estimator lgbm's best error=0.3119
[flaml.automl.logger: 07-15 10:22:51] {2258} INFO - iteration 6, current learner lgbm
[flaml.automl.logger: 07-15 10:22:59] {2442} INFO -  at 53.8s,	estimator lgbm's best error=0.3065,	best estimator lgbm's best error=0.3065
[flaml.automl.logger: 07-15 10:22:59] {2258} INFO - iteration 7, current learner lgbm
[flaml.automl.logger: 07-15 10:23:07] {2442} INFO -  at 61.7s,	estimator lgbm's best error=0.3065,	best estimator lgbm's best error=0.3065
[flaml.automl.logger: 07-15 10:23:07] {2258} INFO - iteration 8, current learner lgbm
[flaml.automl.logger: 07-15 10:23:14] {2442} INFO -  at 69.0s,	estimator lgbm's best error=0.3065,	best estimator lgbm's best error=0.3065
[flaml.automl.logger: 07-15 10:23:14] {2258} INFO - iteration 9, current learner xgboost
[flaml.automl.logger: 07-15 10:23:19] {2442} INFO -  at 73.8s,	estimator xgboost's best error=1.0515,	best estimator lgbm's best error=0.3065
[flaml.automl.logger: 07-15 10:23:19] {2258} INFO - iteration 10, current learner extra_tree
[flaml.automl.logger: 07-15 10:23:25] {2442} INFO -  at 79.7s,	estimator extra_tree's best error=0.5207,	best estimator lgbm's best error=0.3065
[flaml.automl.logger: 07-15 10:23:25] {2258} INFO - iteration 11, current learner xgboost
[flaml.automl.logger: 07-15 10:23:29] {2442} INFO -  at 84.5s,	estimator xgboost's best error=0.6600,	best estimator lgbm's best error=0.3065
[flaml.automl.logger: 07-15 10:23:29] {2258} INFO - iteration 12, current learner extra_tree
[flaml.automl.logger: 07-15 10:23:38] {2442} INFO -  at 93.0s,	estimator extra_tree's best error=0.3316,	best estimator lgbm's best error=0.3065
[flaml.automl.logger: 07-15 10:23:38] {2258} INFO - iteration 13, current learner xgboost
[flaml.automl.logger: 07-15 10:23:43] {2442} INFO -  at 97.8s,	estimator xgboost's best error=0.3751,	best estimator lgbm's best error=0.3065
[flaml.automl.logger: 07-15 10:23:43] {2258} INFO - iteration 14, current learner xgboost
[flaml.automl.logger: 07-15 10:23:48] {2442} INFO -  at 102.8s,	estimator xgboost's best error=0.3751,	best estimator lgbm's best error=0.3065
[flaml.automl.logger: 07-15 10:23:48] {2258} INFO - iteration 15, current learner xgboost
[flaml.automl.logger: 07-15 10:23:52] {2442} INFO -  at 107.4s,	estimator xgboost's best error=0.3751,	best estimator lgbm's best error=0.3065
[flaml.automl.logger: 07-15 10:23:52] {2258} INFO - iteration 16, current learner extra_tree
[flaml.automl.logger: 07-15 10:23:59] {2442} INFO -  at 114.5s,	estimator extra_tree's best error=0.3316,	best estimator lgbm's best error=0.3065
[flaml.automl.logger: 07-15 10:23:59] {2258} INFO - iteration 17, current learner lgbm
[flaml.automl.logger: 07-15 10:24:08] {2442} INFO -  at 123.1s,	estimator lgbm's best error=0.2932,	best estimator lgbm's best error=0.2932
[flaml.automl.logger: 07-15 10:24:08] {2258} INFO - iteration 18, current learner extra_tree
[flaml.automl.logger: 07-15 10:24:23] {2442} INFO -  at 137.7s,	estimator extra_tree's best error=0.2882,	best estimator extra_tree's best error=0.2882
[flaml.automl.logger: 07-15 10:24:23] {2258} INFO - iteration 19, current learner xgboost
[flaml.automl.logger: 07-15 10:24:28] {2442} INFO -  at 143.0s,	estimator xgboost's best error=0.3548,	best estimator extra_tree's best error=0.2882
[flaml.automl.logger: 07-15 10:24:28] {2258} INFO - iteration 20, current learner extra_tree
[flaml.automl.logger: 07-15 10:24:46] {2442} INFO -  at 161.5s,	estimator extra_tree's best error=0.2624,	best estimator extra_tree's best error=0.2624
[flaml.automl.logger: 07-15 10:24:46] {2258} INFO - iteration 21, current learner xgboost
[flaml.automl.logger: 07-15 10:24:52] {2442} INFO -  at 167.6s,	estimator xgboost's best error=0.3523,	best estimator extra_tree's best error=0.2624
[flaml.automl.logger: 07-15 10:24:52] {2258} INFO - iteration 22, current learner extra_tree
[flaml.automl.logger: 07-15 10:25:07] {2442} INFO -  at 182.3s,	estimator extra_tree's best error=0.2624,	best estimator extra_tree's best error=0.2624
[flaml.automl.logger: 07-15 10:25:07] {2258} INFO - iteration 23, current learner extra_tree
[flaml.automl.logger: 07-15 10:25:31] {2442} INFO -  at 205.7s,	estimator extra_tree's best error=0.2584,	best estimator extra_tree's best error=0.2584
[flaml.automl.logger: 07-15 10:25:31] {2258} INFO - iteration 24, current learner extra_tree
[flaml.automl.logger: 07-15 10:25:49] {2442} INFO -  at 224.3s,	estimator extra_tree's best error=0.2584,	best estimator extra_tree's best error=0.2584
[flaml.automl.logger: 07-15 10:25:49] {2258} INFO - iteration 25, current learner extra_tree
[flaml.automl.logger: 07-15 10:26:20] {2442} INFO -  at 255.3s,	estimator extra_tree's best error=0.2534,	best estimator extra_tree's best error=0.2534
[flaml.automl.logger: 07-15 10:26:20] {2258} INFO - iteration 26, current learner extra_tree
[flaml.automl.logger: 07-15 10:26:43] {2442} INFO -  at 278.4s,	estimator extra_tree's best error=0.2534,	best estimator extra_tree's best error=0.2534
[flaml.automl.logger: 07-15 10:26:43] {2258} INFO - iteration 27, current learner extra_tree
[flaml.automl.logger: 07-15 10:27:19] {2442} INFO -  at 314.1s,	estimator extra_tree's best error=0.2508,	best estimator extra_tree's best error=0.2508
[flaml.automl.logger: 07-15 10:27:19] {2258} INFO - iteration 28, current learner extra_tree
[flaml.automl.logger: 07-15 10:27:35] {2442} INFO -  at 330.1s,	estimator extra_tree's best error=0.2508,	best estimator extra_tree's best error=0.2508
[flaml.automl.logger: 07-15 10:27:35] {2258} INFO - iteration 29, current learner lgbm
[flaml.automl.logger: 07-15 10:27:42] {2442} INFO -  at 337.5s,	estimator lgbm's best error=0.2932,	best estimator extra_tree's best error=0.2508
[flaml.automl.logger: 07-15 10:27:42] {2258} INFO - iteration 30, current learner lgbm
[flaml.automl.logger: 07-15 10:27:58] {2442} INFO -  at 353.2s,	estimator lgbm's best error=0.2670,	best estimator extra_tree's best error=0.2508
[flaml.automl.logger: 07-15 10:27:58] {2258} INFO - iteration 31, current learner lgbm
[flaml.automl.logger: 07-15 10:28:25] {2442} INFO -  at 379.8s,	estimator lgbm's best error=0.2670,	best estimator extra_tree's best error=0.2508
[flaml.automl.logger: 07-15 10:28:25] {2258} INFO - iteration 32, current learner extra_tree
[flaml.automl.logger: 07-15 10:29:32] {2442} INFO -  at 447.1s,	estimator extra_tree's best error=0.2492,	best estimator extra_tree's best error=0.2492
[flaml.automl.logger: 07-15 10:29:32] {2258} INFO - iteration 33, current learner lgbm
[flaml.automl.logger: 07-15 10:29:44] {2442} INFO -  at 459.3s,	estimator lgbm's best error=0.2670,	best estimator extra_tree's best error=0.2492
[flaml.automl.logger: 07-15 10:29:44] {2258} INFO - iteration 34, current learner lgbm
[flaml.automl.logger: 07-15 10:30:02] {2442} INFO -  at 477.2s,	estimator lgbm's best error=0.2670,	best estimator extra_tree's best error=0.2492
[flaml.automl.logger: 07-15 10:30:02] {2258} INFO - iteration 35, current learner extra_tree
[flaml.automl.logger: 07-15 10:30:33] {2442} INFO -  at 508.5s,	estimator extra_tree's best error=0.2492,	best estimator extra_tree's best error=0.2492
[flaml.automl.logger: 07-15 10:30:33] {2258} INFO - iteration 36, current learner extra_tree
[flaml.automl.logger: 07-15 10:33:01] {2442} INFO -  at 656.5s,	estimator extra_tree's best error=0.2450,	best estimator extra_tree's best error=0.2450
[flaml.automl.logger: 07-15 10:33:01] {2258} INFO - iteration 37, current learner catboost
[flaml.automl.logger: 07-15 10:33:16] {2442} INFO -  at 671.6s,	estimator catboost's best error=0.2770,	best estimator extra_tree's best error=0.2450
[flaml.automl.logger: 07-15 10:33:16] {2258} INFO - iteration 38, current learner catboost
[flaml.automl.logger: 07-15 10:33:47] {2442} INFO -  at 701.7s,	estimator catboost's best error=0.2770,	best estimator extra_tree's best error=0.2450
[flaml.automl.logger: 07-15 10:33:47] {2258} INFO - iteration 39, current learner catboost
[flaml.automl.logger: 07-15 10:33:59] {2442} INFO -  at 714.1s,	estimator catboost's best error=0.2679,	best estimator extra_tree's best error=0.2450
[flaml.automl.logger: 07-15 10:33:59] {2258} INFO - iteration 40, current learner extra_tree
[flaml.automl.logger: 07-15 10:35:40] {2442} INFO -  at 815.6s,	estimator extra_tree's best error=0.2450,	best estimator extra_tree's best error=0.2450
[flaml.automl.logger: 07-15 10:35:40] {2258} INFO - iteration 41, current learner catboost
[flaml.automl.logger: 07-15 10:36:01] {2442} INFO -  at 835.7s,	estimator catboost's best error=0.2656,	best estimator extra_tree's best error=0.2450
[flaml.automl.logger: 07-15 10:36:01] {2258} INFO - iteration 42, current learner lgbm
[flaml.automl.logger: 07-15 10:36:25] {2442} INFO -  at 860.6s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:36:25] {2258} INFO - iteration 43, current learner xgboost
[flaml.automl.logger: 07-15 10:36:31] {2442} INFO -  at 866.0s,	estimator xgboost's best error=0.3067,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:36:31] {2258} INFO - iteration 44, current learner catboost
[flaml.automl.logger: 07-15 10:37:16] {2442} INFO -  at 910.8s,	estimator catboost's best error=0.2656,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:37:16] {2258} INFO - iteration 45, current learner xgboost
[flaml.automl.logger: 07-15 10:37:45] {2442} INFO -  at 939.7s,	estimator xgboost's best error=0.2969,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:37:45] {2258} INFO - iteration 46, current learner lgbm
[flaml.automl.logger: 07-15 10:39:05] {2442} INFO -  at 1019.8s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:39:05] {2258} INFO - iteration 47, current learner xgboost
[flaml.automl.logger: 07-15 10:39:11] {2442} INFO -  at 1025.7s,	estimator xgboost's best error=0.2969,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:39:11] {2258} INFO - iteration 48, current learner lgbm
[flaml.automl.logger: 07-15 10:39:26] {2442} INFO -  at 1041.3s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:39:26] {2258} INFO - iteration 49, current learner lgbm
[flaml.automl.logger: 07-15 10:41:07] {2442} INFO -  at 1142.2s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:41:07] {2258} INFO - iteration 50, current learner extra_tree
[flaml.automl.logger: 07-15 10:44:45] {2442} INFO -  at 1360.6s,	estimator extra_tree's best error=0.2438,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:44:45] {2258} INFO - iteration 51, current learner lgbm
[flaml.automl.logger: 07-15 10:44:59] {2442} INFO -  at 1374.0s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:44:59] {2258} INFO - iteration 52, current learner lgbm
[flaml.automl.logger: 07-15 10:45:13] {2442} INFO -  at 1388.3s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:45:13] {2258} INFO - iteration 53, current learner lgbm
[flaml.automl.logger: 07-15 10:45:59] {2442} INFO -  at 1434.1s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:45:59] {2258} INFO - iteration 54, current learner lgbm
[flaml.automl.logger: 07-15 10:46:32] {2442} INFO -  at 1466.8s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:46:32] {2258} INFO - iteration 55, current learner xgboost
[flaml.automl.logger: 07-15 10:46:38] {2442} INFO -  at 1473.1s,	estimator xgboost's best error=0.2969,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:46:38] {2258} INFO - iteration 56, current learner lgbm
[flaml.automl.logger: 07-15 10:46:55] {2442} INFO -  at 1490.3s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:46:55] {2258} INFO - iteration 57, current learner lgbm
[flaml.automl.logger: 07-15 10:47:28] {2442} INFO -  at 1522.7s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:47:28] {2258} INFO - iteration 58, current learner lgbm
[flaml.automl.logger: 07-15 10:47:51] {2442} INFO -  at 1546.6s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:47:51] {2258} INFO - iteration 59, current learner lgbm
[flaml.automl.logger: 07-15 10:48:51] {2442} INFO -  at 1606.4s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:48:51] {2258} INFO - iteration 60, current learner xgboost
[flaml.automl.logger: 07-15 10:48:59] {2442} INFO -  at 1614.0s,	estimator xgboost's best error=0.2697,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:48:59] {2258} INFO - iteration 61, current learner xgboost
[flaml.automl.logger: 07-15 10:49:06] {2442} INFO -  at 1620.8s,	estimator xgboost's best error=0.2697,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:49:06] {2258} INFO - iteration 62, current learner xgboost
[flaml.automl.logger: 07-15 10:49:18] {2442} INFO -  at 1632.8s,	estimator xgboost's best error=0.2697,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:49:18] {2258} INFO - iteration 63, current learner xgboost
[flaml.automl.logger: 07-15 10:49:24] {2442} INFO -  at 1638.7s,	estimator xgboost's best error=0.2697,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:49:24] {2258} INFO - iteration 64, current learner lgbm
[flaml.automl.logger: 07-15 10:49:35] {2442} INFO -  at 1649.9s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:49:35] {2258} INFO - iteration 65, current learner xgboost
[flaml.automl.logger: 07-15 10:49:48] {2442} INFO -  at 1663.0s,	estimator xgboost's best error=0.2697,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:49:48] {2258} INFO - iteration 66, current learner xgboost
[flaml.automl.logger: 07-15 10:49:53] {2442} INFO -  at 1668.2s,	estimator xgboost's best error=0.2697,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:49:53] {2258} INFO - iteration 67, current learner xgboost
[flaml.automl.logger: 07-15 10:50:11] {2442} INFO -  at 1686.6s,	estimator xgboost's best error=0.2596,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:50:11] {2258} INFO - iteration 68, current learner lgbm
[flaml.automl.logger: 07-15 10:50:50] {2442} INFO -  at 1725.2s,	estimator lgbm's best error=0.2344,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:50:50] {2258} INFO - iteration 69, current learner xgboost
[flaml.automl.logger: 07-15 10:50:57] {2442} INFO -  at 1731.9s,	estimator xgboost's best error=0.2596,	best estimator lgbm's best error=0.2344
[flaml.automl.logger: 07-15 10:50:57] {2258} INFO - iteration 70, current learner xgboost
[flaml.automl.logger: 07-15 10:53:15] {2442} INFO -  at 1869.9s,	estimator xgboost's best error=0.2340,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 10:53:15] {2258} INFO - iteration 71, current learner xgboost
[flaml.automl.logger: 07-15 10:54:18] {2442} INFO -  at 1933.4s,	estimator xgboost's best error=0.2340,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 10:54:18] {2258} INFO - iteration 72, current learner catboost
[flaml.automl.logger: 07-15 10:54:32] {2442} INFO -  at 1947.0s,	estimator catboost's best error=0.2656,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 10:54:32] {2258} INFO - iteration 73, current learner xgboost
[flaml.automl.logger: 07-15 10:57:23] {2442} INFO -  at 2118.2s,	estimator xgboost's best error=0.2340,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 10:57:23] {2258} INFO - iteration 74, current learner xgboost
[flaml.automl.logger: 07-15 10:59:08] {2442} INFO -  at 2223.5s,	estimator xgboost's best error=0.2340,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 10:59:08] {2258} INFO - iteration 75, current learner lgbm
[flaml.automl.logger: 07-15 10:59:20] {2442} INFO -  at 2235.4s,	estimator lgbm's best error=0.2344,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 10:59:20] {2258} INFO - iteration 76, current learner lgbm
[flaml.automl.logger: 07-15 10:59:30] {2442} INFO -  at 2245.4s,	estimator lgbm's best error=0.2344,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 10:59:30] {2258} INFO - iteration 77, current learner xgboost
[flaml.automl.logger: 07-15 11:02:11] {2442} INFO -  at 2405.7s,	estimator xgboost's best error=0.2340,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 11:02:11] {2258} INFO - iteration 78, current learner xgb_limitdepth
[flaml.automl.logger: 07-15 11:02:18] {2442} INFO -  at 2413.1s,	estimator xgb_limitdepth's best error=0.2736,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 11:02:18] {2258} INFO - iteration 79, current learner xgb_limitdepth
[flaml.automl.logger: 07-15 11:02:25] {2442} INFO -  at 2419.8s,	estimator xgb_limitdepth's best error=0.2736,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 11:02:25] {2258} INFO - iteration 80, current learner xgb_limitdepth
[flaml.automl.logger: 07-15 11:02:32] {2442} INFO -  at 2426.9s,	estimator xgb_limitdepth's best error=0.2736,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 11:02:32] {2258} INFO - iteration 81, current learner xgb_limitdepth
[flaml.automl.logger: 07-15 11:02:39] {2442} INFO -  at 2434.4s,	estimator xgb_limitdepth's best error=0.2736,	best estimator xgboost's best error=0.2340
[flaml.automl.logger: 07-15 11:02:39] {2258} INFO - iteration 82, current learner xgb_limitdepth

In [8]:
# hago la prediccion en test
y_pred = automl.predict(X_test)
result = test_df[["product_id", "target"]].copy()
result["y_pred"] = y_pred
result = result.groupby("product_id").sum().reset_index()
result["error"] = np.abs(result["y_pred"] - result["target"])
total_error = result["error"].sum() / result["target"].sum()
print(f"Total error: {total_error}")
result

Total error: 0.09258218854665756

     product_id       target       y_pred      error
0         20001  1504.688599  1449.788330  54.900269
1         20002  1087.308594  1084.819824   2.488770
2         20003   892.501282   848.983643  43.517639
3         20004   637.900024   670.871094  32.971069
4         20005   593.244446   587.352966   5.891479
..          ...          ...          ...        ...
775       21263     0.012700     0.164697   0.151997
776       21265     0.050070     0.245678   0.195608
777       21266     0.051210     0.245678   0.194468
778       21267     0.015690     0.248813   0.233123
779       21276     0.008920     0.221045   0.212125

[780 rows x 4 columns]

In [11]:
kaggle_date_id = 35
final_test_df = df[df["date_id"] == kaggle_date_id]

# reentreno el mejor modelo con todo el train
#best_model = automl.model
#best_model.fit(X=X_final_train, y=y_final_train)

y_pred_kaggle = automl.predict(final_test_df.drop("target", axis=1))
result_kaggle = final_test_df[["product_id", "date_id", "target"]].copy()
result_kaggle["y_pred"] = y_pred_kaggle
result_kaggle = result_kaggle.groupby("product_id").sum().reset_index()
submission = result_kaggle[["product_id", "y_pred"]].copy()
submission.columns = ["product_id", "tn"]
submission.to_csv(f"submission_automl_{time_budget}s.csv", index=False)
submission

     product_id           tn
0         20001  1504.566528
1         20002  1256.016479
2         20003   933.770203
3         20004   696.926392
4         20005   679.627991
..          ...          ...
775       21263     0.284209
776       21265     0.287332
777       21266     0.287332
778       21267     0.276655
779       21276     0.272964

[780 rows x 2 columns]