In [12]:
import pandas as pd
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor


DATA_FOLDER = "./"

df = pd.read_pickle(DATA_FOLDER + "df_fe_epic_light_best_customers_50c.pickle")
#df = pd.read_pickle(DATA_FOLDER + "df_fe_epic_light_grouped.pickle")
if not "serie_id" in df.columns:
    df["serie_id"] = df["product_id"].astype(str) + "_" + df["customer_id"].astype(str)

product_ids = pd.read_csv(DATA_FOLDER + "product_id_apredecir201912.txt", sep="\t")[
    "product_id"
].tolist()

In [13]:
import numpy as np
numeric_df = df.select_dtypes(include=[np.number])
total_infs = np.isinf(numeric_df.values).sum()
print(f"Total infs: {total_infs}")
df[numeric_df.columns] = df[numeric_df.columns].replace([np.inf, -np.inf], np.nan)
df['fecha'] = df['fecha'].apply(lambda x: x.to_timestamp('M'))  # último día del mes

Total infs: 0

In [14]:
TEST_DATE = 35

def get_indexes(df, test_date=TEST_DATE):
    test_index = df.index[df['date_id'] == test_date]
    train_index = df.index[df['date_id'] <= test_date]
    train_scaler_index = df.index[df['date_id'] <= test_date]
    return test_index, train_index, train_scaler_index
df["target"] = df.groupby(['customer_id', 'product_id'])['tn'].shift(-2)

test_index, train_index, train_scaler_index = get_indexes(df)
train_df = df.loc[train_index].copy()
test_df = df.loc[test_index].copy()

/tmp/ipykernel_109478/2186123290.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["target"] = df.groupby(['customer_id', 'product_id'])['tn'].shift(-2)

In [15]:

static_features_df = pd.DataFrame({
    'cat1': df.groupby('product_id')['cat1'].first(),
    'cat2': df.groupby('product_id')['cat2'].first(),
    'cat3': df.groupby('product_id')['cat3'].first(),
    'brand': df.groupby('product_id')['brand'].first(),
    'sku_size': df.groupby('product_id')['sku_size'].first(),
}).reset_index()
# drop this from test)DF

train_df_no_static = train_df.drop(columns=['cat1', 'cat2', 'cat3', 'brand', 'sku_size'])


# cambviar dtypes int16 o int8 a int32 en train_df_no_static
for column in train_df_no_static.columns:
    if train_df_no_static[column].dtype == "int16" or train_df_no_static[column].dtype == "int8":
        train_df_no_static[column] = train_df_no_static[column].astype("int32")    
# agrego la categoria "missing" y hago fill nan con missing
for column in static_features_df.columns:
    if static_features_df[column].dtype.name == "category":
        static_features_df[column] = static_features_df[column].cat.add_categories("missing")
    static_features_df[column] = static_features_df[column].fillna("missing").astype("category")
static_features_df.isna().sum()

product_id    0
cat1          0
cat2          0
cat3          0
brand         0
sku_size      0
dtype: int64

In [16]:
agg_dict = {}
for col in train_df_no_static.columns:
    if col in ['product_id', 'fecha']:
        continue
    elif col == 'tn':
        agg_dict[col] = 'sum'
    elif train_df_no_static[col].dtype == 'O':
        agg_dict[col] = 'first'
    else:
        agg_dict[col] = 'mean'

# Calcular ticket_promedio y ticket_promedio_con_ceros, total_customers y total_customer_con_ceros
def custom_agg(group):
    tn_no_cero = group[group['tn'] != 0]
    ticket_promedio = tn_no_cero['tn'].mean() if not tn_no_cero.empty else 0
    ticket_promedio_con_ceros = group['tn'].mean()
    total_customers = tn_no_cero['customer_id'].nunique()
    total_customer_con_ceros = group['customer_id'].nunique()
    return pd.Series({
        'ticket_promedio': ticket_promedio,
        'ticket_promedio_con_ceros': ticket_promedio_con_ceros,
        'total_customers': total_customers,
        'total_customer_con_ceros': total_customer_con_ceros
    })

agg_dict_custom = {**agg_dict}
train_df_grouped = train_df_no_static.groupby(['product_id', 'fecha']).agg(agg_dict_custom).reset_index()

# Merge custom aggregations
custom_aggs = train_df_no_static.groupby(['product_id', 'fecha']).apply(custom_agg).reset_index()
train_df_grouped = train_df_grouped.merge(custom_aggs, on=['product_id', 'fecha'], how='left')
train_df_grouped

/tmp/ipykernel_109478/3666341461.py:30: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  custom_aggs = train_df_no_static.groupby(['product_id', 'fecha']).apply(custom_agg).reset_index()

,product_id,fecha,customer_id,periodo_min_producto,periodo_max_producto,periodo_min_customer,periodo_max_customer,plan_precios_cuidados,cust_request_qty,cust_request_tn,...,tn_total_vendidas,tn_customer_weight,tn_product_vendidas,tn_product_weight,serie_id,target,ticket_promedio,ticket_promedio_con_ceros,total_customers,total_customer_con_ceros
0,20001,2017-01-31,9828.960784,2017-01-01,2019-12-01,2017-01-01,2019-11-27 08:09:36,0.0,9.392157,18.386806,...,34057.316406,0.019608,934.772217,2.744703e-02,20001_0,25.556032,23.968519,18.328867,39.0,51.0
1,20001,2017-02-28,9828.960784,2017-01-01,2019-12-01,2017-01-01,2019-11-27 08:09:36,0.0,8.470588,16.347488,...,34568.652344,0.019608,798.016174,2.308496e-02,20001_0,20.979633,19.000385,15.647376,42.0,51.0
2,20001,2017-03-31,9828.960784,2017-01-01,2019-12-01,2017-01-01,2019-11-27 08:09:36,0.0,9.980392,26.093077,...,46040.597656,0.019608,1303.357666,2.830888e-02,20001_0,29.454927,34.298885,25.556036,38.0,51.0
3,20001,2017-04-30,9828.960784,2017-01-01,2019-12-01,2017-01-01,2019-11-27 08:09:36,0.0,5.470588,22.214594,...,39625.523438,0.019608,1069.961304,2.700182e-02,20001_0,29.805204,32.423069,20.979633,33.0,51.0
4,20001,2017-05-31,9828.960784,2017-01-01,2019-12-01,2017-01-01,2019-11-27 08:09:36,0.0,13.745098,30.405674,...,45579.632812,0.019608,1502.201294,3.295773e-02,20001_0,20.209291,34.140938,29.454927,44.0,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31517,21295,2017-01-31,9828.960784,2017-01-01,2017-01-01,2017-01-01,2019-11-27 08:09:36,0.0,0.019608,0.000137,...,34057.316406,0.019608,0.006990,2.052422e-07,21295_0,NaN,0.006990,0.000137,1.0,51.0
31518,21296,2017-08-31,9828.960784,2017-08-01,2017-08-01,2017-01-01,2019-11-27 08:09:36,0.0,0.019608,0.000128,...,40206.382812,0.019608,0.006510,1.619146e-07,21296_0,NaN,0.006510,0.000128,1.0,51.0
31519,21297,2017-01-31,9828.960784,2017-01-01,2017-01-01,2017-01-01,2019-11-27 08:09:36,0.0,0.019608,0.000114,...,34057.316406,0.019608,0.005790,1.700075e-07,21297_0,NaN,0.005790,0.000114,1.0,51.0
31520,21298,2017-08-31,9828.960784,2017-08-01,2017-08-01,2017-01-01,2019-11-27 08:09:36,0.0,0.019608,0.000112,...,40206.382812,0.019608,0.005730,1.425147e-07,21298_0,NaN,0.005730,0.000112,1.0,51.0
31521,21299,2017-08-31,9828.960784,2017-08-01,2017-08-01,2017-01-01,2019-11-27 08:09:36,0.0,0.019608,0.000107,...,40206.382812,0.019608,0.005460,1.357993e-07,21299_0,NaN,0.005460,0.000107,1.0,51.0

In [17]:

static_features_df = pd.DataFrame({
    'cat1': df.groupby('product_id')['cat1'].first(),
    'cat2': df.groupby('product_id')['cat2'].first(),
    'cat3': df.groupby('product_id')['cat3'].first(),
    'brand': df.groupby('product_id')['brand'].first(),
    'sku_size': df.groupby('product_id')['sku_size'].first(),
}).reset_index()
# drop this from test)DF


# cambviar dtypes int16 o int8 a int32 en train_df_no_static
for column in train_df_no_static.columns:
    if train_df_no_static[column].dtype == "int16" or train_df_no_static[column].dtype == "int8":
        train_df_no_static[column] = train_df_no_static[column].astype("int32")    
# agrego la categoria "missing" y hago fill nan con missing
for column in static_features_df.columns:
    if static_features_df[column].dtype.name == "category":
        static_features_df[column] = static_features_df[column].cat.add_categories("missing")
    static_features_df[column] = static_features_df[column].fillna("missing").astype("category")
static_features_df.isna().sum()


train_data = TimeSeriesDataFrame.from_data_frame(
    train_df_grouped.drop(columns=['target'], errors="ignore"),  # No necesito la columna target en train_data
    id_column="product_id",
    timestamp_column="fecha",
    static_features_df=static_features_df
)
train_data.head()


predictor = TimeSeriesPredictor(
    prediction_length=2,
    target="ticket_promedio",
    freq="ME",
)


predictor.fit(
    train_data,
    #presets="best_quality",
    presets="medium_quality",
    time_limit=600,
)
preds_tn_promedio = predictor.predict(train_data)

Beginning AutoGluon training... Time limit = 600s
AutoGluon will save models to '/home/fede/programacion/labo3/AutogluonModels/ag-20250701_232455'
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.3
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #65-Ubuntu SMP PREEMPT_DYNAMIC Mon May 19 17:15:03 UTC 2025
CPU Count:          8
GPU Count:          0
Memory Avail:       4.18 GB / 15.32 GB (27.3%)
Disk Space Avail:   67.85 GB / 575.67 GB (11.8%)
===================================================
Setting presets to: medium_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'freq': 'ME',
 'hyperparameters': 'light',
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 2,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'ticket_promedio',
 'time_limit': 600,
 'verbosity': 2}

train_data with frequency 'IRREG' has been resampled to frequency 'ME'.
Provided train_data has 31522 rows, 1233 time series. Median time series length is 31 (min=1, max=36).
	Removing 132 short time series from train_data. Only series with length >= 7 will be used for training.
	After filtering, train_data has 31021 rows, 1101 time series. Median time series length is 36 (min=7, max=36).

Provided data contains following columns:
	target: 'ticket_promedio'
	past_covariates:
		categorical:        ['serie_id']
		continuous (float): ['customer_id', 'plan_precios_cuidados', 'cust_request_qty', 'cust_request_tn', 'tn', 'stock_final', ...]
	static_features:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): []

AutoGluon will ignore following non-numeric/non-informative columns:
	ignored covariates:      ['periodo_max_customer', 'periodo_max_producto', 'periodo_min_customer', 'periodo_min_producto', 'tn_customer_vendidas', 'tn_product_vendidas']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2025-07-01 20:25:18
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'Chronos[bolt_small]', 'TemporalFusionTransformer']
Training timeseries model Naive. Training for up to 64.5s of the 580.3s of remaining time.
	-0.3326       = Validation score (-WQL)
	0.12    s     = Training runtime
	4.74    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive. Training for up to 71.9s of the 575.4s of remaining time.
	-0.3252       = Validation score (-WQL)
	0.08    s     = Training runtime
	1.02    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular. Training for up to 82.0s of the 574.3s of remaining time.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-0.2706       = Validation score (-WQL)
	1.81    s     = Training runtime
	0.13    s     = Validation (prediction) runtime
Training timeseries model DirectTabular. Training for up to 95.4s of the 572.4s of remaining time.
	-0.2723       = Validation score (-WQL)
	11.18   s     = Training runtime
	0.36    s     = Validation (prediction) runtime
Training timeseries model ETS. Training for up to 112.2s of the 560.8s of remaining time.
	Warning: ETS/W0 failed for 52 time series (4.7%). Fallback model SeasonalNaive was used for these time series.
	-0.2658       = Validation score (-WQL)
	0.09    s     = Training runtime
	10.44   s     = Validation (prediction) runtime
Training timeseries model Theta. Training for up to 137.6s of the 550.3s of remaining time.
	-0.2568       = Validation score (-WQL)
	0.09    s     = Training runtime
	1.42    s     = Validation (prediction) runtime
Training timeseries model Chronos[bolt_small]. Training for up to 182.9s of the 548.8s of remaining time.
	-0.2528       = Validation score (-WQL)
	0.08    s     = Training runtime
	3.24    s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer. Training for up to 272.7s of the 545.5s of remaining time.
	-0.2417       = Validation score (-WQL)
	246.36  s     = Training runtime
	1.35    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'Chronos[bolt_small]': 0.2, 'RecursiveTabular': 0.07, 'TemporalFusionTransformer': 0.59, 'Theta': 0.14}
	-0.2347       = Validation score (-WQL)
	1.44    s     = Training runtime
	6.13    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'Chronos[bolt_small]', 'TemporalFusionTransformer', 'WeightedEnsemble']
Total runtime: 284.15 s
Best model: WeightedEnsemble
Best model score: -0.2347
data with frequency 'IRREG' has been resampled to frequency 'ME'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble
	Warning: Theta/W0 failed for 78 time series (6.3%). Fallback model SeasonalNaive was used for these time series.
Warning: 20 time series (1.6%) are shorter than 1 and cannot be predicted by RecursiveTabular/W0. Fallback model SeasonalNaive is used for these time series.
Warning: No path was specified for model, defaulting to: /home/fede/programacion/labo3/AutogluonModels/ag-20250701_233042/

In [18]:

static_features_df = pd.DataFrame({
    'cat1': df.groupby('product_id')['cat1'].first(),
    'cat2': df.groupby('product_id')['cat2'].first(),
    'cat3': df.groupby('product_id')['cat3'].first(),
    'brand': df.groupby('product_id')['brand'].first(),
    'sku_size': df.groupby('product_id')['sku_size'].first(),
}).reset_index()
# drop this from test)DF
 
# agrego la categoria "missing" y hago fill nan con missing
for column in static_features_df.columns:
    if static_features_df[column].dtype.name == "category":
        static_features_df[column] = static_features_df[column].cat.add_categories("missing")
    static_features_df[column] = static_features_df[column].fillna("missing").astype("category")
static_features_df.isna().sum()

train_data = TimeSeriesDataFrame.from_data_frame(
    train_df_grouped.drop(columns=['target'], errors="ignore"),  # No necesito la columna target en train_data
    id_column="product_id",
    timestamp_column="fecha",
    static_features_df=static_features_df
)
train_data.head()


predictor = TimeSeriesPredictor(
    prediction_length=2,
    target="total_customers",
    freq="ME",
)


predictor.fit(
    train_data,
    presets="medium_quality",
    time_limit=600,
)
preds_total_customer = predictor.predict(train_data)

Beginning AutoGluon training... Time limit = 600s
AutoGluon will save models to '/home/fede/programacion/labo3/AutogluonModels/ag-20250701_233043'
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.3
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #65-Ubuntu SMP PREEMPT_DYNAMIC Mon May 19 17:15:03 UTC 2025
CPU Count:          8
GPU Count:          0
Memory Avail:       2.66 GB / 15.32 GB (17.4%)
Disk Space Avail:   67.70 GB / 575.67 GB (11.8%)
===================================================
Setting presets to: medium_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'freq': 'ME',
 'hyperparameters': 'light',
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 2,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'total_customers',
 'time_limit': 600,
 'verbosity': 2}

train_data with frequency 'IRREG' has been resampled to frequency 'ME'.
Provided train_data has 31522 rows, 1233 time series. Median time series length is 31 (min=1, max=36).
	Removing 132 short time series from train_data. Only series with length >= 7 will be used for training.
	After filtering, train_data has 31021 rows, 1101 time series. Median time series length is 36 (min=7, max=36).

Provided data contains following columns:
	target: 'total_customers'
	past_covariates:
		categorical:        ['serie_id']
		continuous (float): ['customer_id', 'plan_precios_cuidados', 'cust_request_qty', 'cust_request_tn', 'tn', 'stock_final', ...]
	static_features:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): []

AutoGluon will ignore following non-numeric/non-informative columns:
	ignored covariates:      ['periodo_max_customer', 'periodo_max_producto', 'periodo_min_customer', 'periodo_min_producto', 'tn_customer_vendidas', 'tn_product_vendidas']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2025-07-01 20:31:08
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'Chronos[bolt_small]', 'TemporalFusionTransformer']
Training timeseries model Naive. Training for up to 64.3s of the 578.3s of remaining time.
	-0.2495       = Validation score (-WQL)
	0.13    s     = Training runtime
	6.40    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive. Training for up to 71.5s of the 571.8s of remaining time.
	-0.3144       = Validation score (-WQL)
	0.14    s     = Training runtime
	1.40    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular. Training for up to 81.5s of the 570.3s of remaining time.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-0.2363       = Validation score (-WQL)
	2.34    s     = Training runtime
	0.16    s     = Validation (prediction) runtime
Training timeseries model DirectTabular. Training for up to 94.6s of the 567.7s of remaining time.
	-0.2541       = Validation score (-WQL)
	26.05   s     = Training runtime
	0.99    s     = Validation (prediction) runtime
Training timeseries model ETS. Training for up to 108.1s of the 540.7s of remaining time.
	Warning: ETS/W0 failed for 51 time series (4.6%). Fallback model SeasonalNaive was used for these time series.
	-0.2466       = Validation score (-WQL)
	0.12    s     = Training runtime
	10.79   s     = Validation (prediction) runtime
Training timeseries model Theta. Training for up to 132.4s of the 529.8s of remaining time.
	-0.2446       = Validation score (-WQL)
	0.11    s     = Training runtime
	1.64    s     = Validation (prediction) runtime
Training timeseries model Chronos[bolt_small]. Training for up to 176.0s of the 528.0s of remaining time.
	-0.2444       = Validation score (-WQL)
	0.10    s     = Training runtime
	3.83    s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer. Training for up to 262.0s of the 524.1s of remaining time.
	-0.2271       = Validation score (-WQL)
	232.04  s     = Training runtime
	1.67    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'Naive': 0.16, 'RecursiveTabular': 0.28, 'TemporalFusionTransformer': 0.56}
	-0.2185       = Validation score (-WQL)
	2.07    s     = Training runtime
	8.24    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'Chronos[bolt_small]', 'TemporalFusionTransformer', 'WeightedEnsemble']
Total runtime: 290.23 s
Best model: WeightedEnsemble
Best model score: -0.2185
data with frequency 'IRREG' has been resampled to frequency 'ME'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble
Warning: 20 time series (1.6%) are shorter than 1 and cannot be predicted by RecursiveTabular/W0. Fallback model SeasonalNaive is used for these time series.
Warning: No path was specified for model, defaulting to: /home/fede/programacion/labo3/AutogluonModels/ag-20250701_233632/

In [22]:
# la prediccion es la columna mean del ultimo timestamp para cada product_id
predictions = preds_tn_promedio.groupby('item_id').last()['mean'].reset_index()
predictions = predictions.rename(columns={'item_id': 'product_id', "mean": "mean_ticket_promedio"})
predictions["total_customers"] = preds_total_customer.groupby('item_id').last()['mean'].reset_index()['mean']

predictions["prediction"] = predictions["mean_ticket_promedio"] * (predictions["total_customers"]-0)
# le agrego la columna target de test_df mergeando por product_id
test_df_grouped = test_df.groupby(['product_id', 'fecha']).agg({
    'target': 'sum'
}).reset_index()
predictions = predictions.merge(test_df_grouped[['product_id', 'target']], on='product_id', how='left')
predictions = predictions[predictions["product_id"].isin(product_ids)]



predictions["abs_error"] = abs(predictions['target'] - predictions['prediction'])
import numpy as np
total_error = np.abs(predictions['target'] - predictions['prediction']).sum() / (predictions['target'].sum())
print(f"Total Absolute Error: {total_error:.4f}")
predictions

Total Absolute Error: inf

/tmp/ipykernel_109478/4095548758.py:18: RuntimeWarning: divide by zero encountered in scalar divide
  total_error = np.abs(predictions['target'] - predictions['prediction']).sum() / (predictions['target'].sum())

,product_id,mean_ticket_promedio,total_customers,prediction,target,abs_error
0,20001,35.284177,37.570683,1325.650625,0.0,1325.650625
1,20002,30.379225,34.485828,1047.652718,0.0,1047.652718
2,20003,20.930870,36.679711,767.738278,0.0,767.738278
3,20004,15.183389,36.030392,547.063458,0.0,547.063458
4,20005,17.220930,33.255283,572.686912,0.0,572.686912
...,...,...,...,...,...,...
1197,21263,-0.004804,3.177319,-0.015265,0.0,0.015265
1199,21265,0.019684,3.066418,0.060358,0.0,0.060358
1200,21266,0.017417,3.002886,0.052300,0.0,0.052300
1201,21267,0.019250,1.999940,0.038498,0.0,0.038498
1210,21276,0.005873,1.995724,0.011721,0.0,0.011721

## en test: Total Absolute Error: 0.2178

In [24]:
submission = predictions[['product_id', 'prediction']]
submission.rename(columns={'prediction': 'tn'}, inplace=True)
submission.to_csv(DATA_FOLDER + "submission_autogluon_mean_ticket0.csv", index=False)

/tmp/ipykernel_109478/1844313901.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  submission.rename(columns={'prediction': 'tn'}, inplace=True)